# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TafelNet
name: 0151 - 717 598 45
email: tafelnet@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  TafelNet schlägt die Brücke zwischen digitalem und analogem Krimskrams,
  indem sie den Bedürftigen auf der Straße den Weg zu deiner Straße zeigt,
  wenn du mal was übrig hast.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tafelnet.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: -
# github_username:  -

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - resourcen.md
  - kanäle.md
  - faq.md
  - kontakt.md
  - impressum.md

minima:
  social_links:
    twitter: jekyllrb
    github: jekyll
    stackoverflow: "11111"
    facebook: jekyll
    instagram: jekyll
    linkedin: jekyll
    telegram: jekyll
    youtube: jekyll
    youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    youtube_channel_name: CloudCannon

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
